### ISSUE TITLE
update docker-compose.yml

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/refarch-cloudnative-netflix#2]
image names for eureka and zuul microservices do not correspond with the image name these microservices get built with. Need to remove the 'microservices-' from their image names in the docker compose file

**Comment by osowski** [comment]
Fixed via https://github.com/ibm-cloud-architecture/refarch-cloudnative-netflix/commit/58f9f93f7d9e1de19be72be2b96f7d9b61f23668
